version: '3'
services:
  webapp-demo:
    image: webapp:rc-02.13.23.16-demo
    build: ./webapp
    ports:
      - '${PORTBASE}81:3000'
    restart: always

  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: 'directus'

  cache:
    restart: always
    image: redis:6
    networks:
      - directus

  directus:
    restart: always
    image: directus/directus:latest
    ports:
      - '${PORTBASE}55:8055'
    volumes:
      - uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'
      CORS_ENABLED: 'true'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: '${DB_PASSWORD}'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: 'true'

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      
      EMAIL_FROM: '${EMAIL_FROM}'
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: '${EMAIL_SMTP_HOST}'
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: '${EMAIL_FROM}'
      EMAIL_SMTP_PASSWORD: '${EMAIL_SMTP_PASSWORD}'
      EMAIL_SMTP_POOL: "false"
      EMAIL_SMTP_SECURE: "false"
      
      REFRESH_TOKEN_COOKIE_SAME_SITE: '${REFRESH_TOKEN_COOKIE_SAME_SITE}'
      REFRESH_TOKEN_COOKIE_SECURE: '${REFRESH_TOKEN_COOKIE_SECURE}'
      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      PUBLIC_URL: 'https://${PUBLIC_URL}'

networks:
  directus:

volumes:
  uploads:
  db:
