on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

name: deploy on demo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set demo tag
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: docker-compose.yml
          body: "{{date:MM.DD.HH.mm}}"
      
      - name: Pull Portainer Hook
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ secrets.PORTAINER_PULL_HOOK }}
